CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_users UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL UNIQUE,
  CONSTRAINT pk_categories PRIMARY KEY (id),
  CONSTRAINT uq_categories UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    title VARCHAR(120) NOT NULL,
    confirmed_requests INTEGER,
    created_on TIMESTAMP WITHOUT TIME ZONE,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE,
    description VARCHAR(4000) NOT NULL,
    initiator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    lat NUMERIC,
    lon NUMERIC,
    paid BOOLEAN,
    request_moderation BOOLEAN,
    participant_limit INTEGER NOT NULL,
    state VARCHAR(255) NOT NULL,
    views INTEGER,
    CONSTRAINT event_pk PRIMARY KEY (id),
    CONSTRAINT event_category_fk FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT event_initiator_fk FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    status varchar(64) NOT NULL,
    created TIMESTAMP NOT NULL,
    UNIQUE(requester_id, event_id)
);


CREATE TABLE IF NOT EXISTS compilations (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   pinned BOOLEAN NOT NULL,
   title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_event (
   compilation_id BIGINT NOT NULL,
   event_id BIGINT NOT NULL,
   PRIMARY KEY (compilation_id, event_id),
   FOREIGN KEY (compilation_id) REFERENCES compilations (id),
   FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS event_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    event_id BIGINT NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events(id)
);
