version: '3.1'
services:
  stats-server:
    build: stats-service/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgresewm
    - TZ=Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresewm

  ewm-service:
    build: stats-service/ewm-http-client
    image: ewm-http-client
    container_name: http-client
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresewm
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresewm
